// Generated by CoffeeScript 1.6.3
var Board,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

goog.provide('game.Board');

goog.require('game.Wall');

goog.require('lime.Sprite');

Board = (function(_super) {
  __extends(Board, _super);

  function Board() {
    var down, left, right, top;
    this.walls = [];
    top = new game.Wall([-512, -384], 1024, 'x');
    down = new game.Wall([-512, 379], 1024, 'x');
    left = new game.Wall([-512, -384], 768, 'y');
    right = new game.Wall([507, -384], 768, 'y');
    this.walls.push(top);
    this.walls.push(down);
    this.walls.push(left);
    this.walls.push(right);
    this.walls.push(new game.Wall([-256, -384], 4 * 768 / 5.0, 'y'));
    this.walls.push(new game.Wall([0, -384 / 4], 512, 'x'));
  }

  return Board;

})(lime.Sprite);

game.Board = Board;
