// Generated by CoffeeScript 1.6.3
var CueBall, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

goog.provide('game.CueBall');

goog.require('lime');

goog.require('lime.Circle');

goog.require('lime.Sprite');

goog.require('game');

goog.require('game.Ball');

CueBall = (function(_super) {
  __extends(CueBall, _super);

  function CueBall() {
    _ref = CueBall.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return CueBall;

})(game.Ball);

game.CueBall = CueBall;
