// Generated by CoffeeScript 1.6.3
var Wall;

goog.provide('game.Wall');

goog.require('lime.Sprite');

goog.require('game');

Wall = (function() {
  function Wall(position, length, direction) {
    var THICKNESS;
    THICKNESS = 6;
    this.layer = new lime.Layer().setPosition(position[0], position[1]);
    this.rect = new lime.Sprite().setAnchorPoint([1, 1]);
    this.direction = direction;
    if (direction === 'x') {
      this.rect.setSize(length, THICKNESS);
    } else if (direction === 'y') {
      this.rect.setSize(THICKNESS, length);
    }
    this.rect.setFill('#000');
    this.layer.appendChild(this.rect);
    game.target.appendChild(this.layer);
  }

  Wall.prototype.collidesCircle = function(pos, radius, velocity) {
    var center, cornersq, distance, height, size, width, xdist, ydist;
    center = this.layer.getPosition().clone();
    size = this.rect.getSize();
    width = size.width;
    height = size.height;
    center.x += width / 2;
    center.y += height / 2;
    xdist = Math.abs(center.x - pos.x);
    ydist = Math.abs(center.y - pos.y);
    distance = new goog.math.Vec2(xdist, ydist);
    if (distance.x >= width / 2 + radius) {
      return false;
    }
    if (distance.y >= height / 2 + radius) {
      return false;
    }
    if (distance.x <= width / 2) {
      return true;
    }
    if (distance.y <= height / 2) {
      return true;
    }
    cornersq = (distance.x - this.rect.width / 2) ^ 2 + (distance.y - this.rect.height / 2) ^ 2;
    return cornersq <= radius * radius;
  };

  return Wall;

})();

game.Wall = Wall;
